# Generated by Django 2.2.17 on 2020-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_list', '0003_auto_20201118_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_list',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
