# Generated by Django 2.2.17 on 2020-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_list', '0005_vendor_list_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_list',
            name='estoque',
            field=models.FloatField(null=True),
        ),
    ]
