# Generated by Django 2.2.17 on 2020-11-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_list', '0009_vendor_list_vendor_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_list',
            old_name='vendor_list',
            new_name='vendor',
        ),
    ]
