# Generated by Django 2.2.17 on 2020-11-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_list', '0010_auto_20201120_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_list',
            old_name='vendor',
            new_name='seller',
        ),
    ]
