# Generated by Django 2.2.17 on 2020-11-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_list', '0011_auto_20201120_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_list',
            old_name='item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vendor_list',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='vendor_list',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendor_list',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vendor_list',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='vendor_list',
            name='stock',
        ),
        migrations.AddField(
            model_name='vendor_list',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('stock', models.IntegerField(null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor_list.Vendor_List')),
            ],
        ),
    ]
